spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cosmocats
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

feature:
  cosmoCats:
    enabled: true
  kittyProducts:
    enabled: false

security:
  api-key:
    header-name: X-API-KEY
    value: "cosmo-cats-api-key"
    paths: /api/v1/products/**
  jwt:
    secret: "cosmo-cats-super-duper-muper-puper-secret"
